const Data = [
    {
        Brand: "Nom Nom",
        Name: "Beef Mash",
        Protein: "77",
        Fat: "40",
        Carbohydrates: "111",
        Img: "bowl_beef_square.png",
    },
    {
        Brand: "Nom Nom",
        Name: "Chicken Cuisine",
        Protein: "80",
        Fat: "56",
        Carbohydrates: "71",
        Img: "bowl_chicken_square.png",
    },
    {
        Brand: "Nom Nom",
        Name: "Turkey Fare",
        Protein: "78",
        Fat: "41",
        Carbohydrates:"109",
        Img: "bowl_turkey_square.png",
    },
    {
        Brand: "Nom Nom",
        Name: "Pork Potluck",
        Protein: "76",
        Fat: "48",
        Carbohydrates: "93",
        Img: "bowl_pork_square.png",
    },
    {
        Brand: "Blue Buffalo",
        Name: "Blue Buffalo ® Wilderness ™ Chicken",
        Protein: "99",
        Fat: "44",
        Carbohydrates: "79",
        MinProtein: "34%",
        MinFat: "15%",
        KCal: "3599",
        Img: "blue_buffalo_chicken.jpg",
    },    
    {
        Brand: "Blue Buffalo",
        Name: "Blue Buffalo ® Wilderness ™ Duck",
        Protein: "99",
        Fat: "44",
        Carbohydrates: "79",        
        MinProtein: "34%",
        MinFat: "15%",
        KCal: "3596",
        Img: "blue_buffalo_duck.jpg",
    },    
    {
        Brand: "Blue Buffalo",
        Name: "Blue Buffalo ® Wilderness ™ Salmon",
        Protein: "99",
        Fat: "45",
        Carbohydrates: "79",
        MinProtein: "34%",
        MinFat: "15%",
        KCal: "3592",
        Img: "blue_buffalo_salmon.jpg",
    },
]

export default Data;