const Data = [
    {
        Brand: "Nom Nom",
        Name: "Beef Mash",
        Protein: "77",
        Fat: "40",
        Carbohydrates: "111",
        Img: "bowl_beef_square.png",
    },
    {
        Brand: "Nom Nom",
        Name: "Chicken Cuisine",
        Protein: "80",
        Fat: "56",
        Carbohydrates: "71",
        Img: "bowl_chicken_square.png",
    },
    {
        Brand: "Nom Nom",
        Name: "Turkey Fare",
        Protein: "78",
        Fat: "41",
        Carbohydrates:"109",
        Img: "bowl_turkey_square.png",
    },
    {
        Brand: "Nom Nom",
        Name: "Pork Potluck",
        Protein: "76",
        Fat: "48",
        Carbohydrates: "93",
        Img: "bowl_pork_square.png",
    },
    {
        Brand: "Blue Buffalo",
        Name: "Blue Buffalo ® Wilderness ™ Chicken",
        Protein: "99",
        Fat: "44",
        Carbohydrates: "79",
        MinProtein: "34%",
        MinFat: "15%",
        KCal: "3599",
        Img: "blue_buffalo_chicken.jpg",
    },    
    {
        Brand: "Blue Buffalo",
        Name: "Blue Buffalo ® Wilderness ™ Duck",
        Protein: "99",
        Fat: "44",
        Carbohydrates: "79",        
        MinProtein: "34%",
        MinFat: "15%",
        KCal: "3596",
        Img: "blue_buffalo_duck.jpg",
    },    
    {
        Brand: "Blue Buffalo",
        Name: "Blue Buffalo ® Wilderness ™ Salmon",
        Protein: "99",
        Fat: "45",
        Carbohydrates: "79",
        MinProtein: "34%",
        MinFat: "15%",
        KCal: "3592",
        Img: "blue_buffalo_salmon.jpg",
    },
    {
        Brand: "Earthborn",
        Name: "EarthBorn Holistic ® Adult Vantage",
        Protein: "67",
        Fat: "37",
        Carbohydrates: "129",
        MinProtein: "22%",
        MinFat: "12%",
        KCal: "3515",
        Img: "earthborn_holistic.jpg",
    },
    {
        Brand: "Earthborn",
        Name: "Earthborn Holistic ® Weight Control",
        Protein: "86",
        Fat: "26",
        Carbohydrates: "137",
        MinProtein: "25%",
        MinFat: "7%",
        KCal: "3090",
        Img: "earthborn_holistic_wc.jpg",
    },
    {
        Brand: "Hills",
        Name: "Hill's ® Chicken & Brown Rice",
        Protein: "54",
        Fat: "40",
        Carbohydrates: "135",
        MinProtein: "19%",
        MinFat: "14%",
        KCal: "3784",
        Img: "hill_chicken.jpg",
    },
    {
        Brand: "Hills",
        Name: "Hill's ® Grain-Free Chicken & Potato",
        Protein: "58",
        Fat: "44",
        Carbohydrates: "122",
        MinProtein: "12%",
        MinFat: "16%",
        KCal: "3891",
        Img: "hill_chicken_grainfree.jpg",
    },
]

export default Data;